name: Tests

on: [push]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - run: npx nx run-many --target=lint --all
      - run: npx nx run-many --target=build --all --prod

